### PR TITLE
Add the posibility to configure comand line parameters

### PR DESCRIPTION
**Pull request by jdeanquin-dg**
Hey

I had some issue with PhatomJS retrieving some CSS files over HTTPS. I needed to send PhantonJs the following command line --ssl-protocol=any and I didn't find a way to do it with the current Implementation. Let me know if you think there is another way to do it or If you feel like you can incorporate the change

Thanks!

### CODE REVIEW

**Review by Dmitry-Shweikus — APPROVED** [review]

**Comment by Dmitry-Shweikus** [comment]
---

**Comment by jdeanquin-dg** [comment]
Hello @Dmitry-Shweikus thanks for approving the change. I was wondering if you have an idea on when you are going to merge it so I can discard my fork. Also, do you plan to release in the near future? I would like to use the lib directly from repos so it still linked to the base code instead of uploading the snapshot to my artifactory.

Thanks!

**Comment by Dmitry-Shweikus** [comment]
Hello @jdeanquin-dg . Currently i don't plan any evolution of the project.

**Review by Jarlakxen — APPROVED** [review]

**Comment by jdeanquin-dg** [comment]
Hello @Jarlakxen a quick question. Do you have in mind to release 2.9 in a near future?

Thanks!

**Comment by Jarlakxen** [comment]
Hi @jdeanquin-dg! I will try to do it, this weekend. =)

**Comment by Jarlakxen** [comment]
@jdeanquin-dg  I just release 2.9

**Comment by jdeanquin-dg** [comment]
Thank you very much!

**Pull request merged**
